// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import dotenv from "dotenv";

// Load .env.local so the Prisma CLI uses the Supabase DATABASE_URL
// (which must take precedence over the local Prisma Postgres in .env).
// Next.js already prefers .env.local at runtime; this mirrors that for the CLI.
dotenv.config({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must run against the DIRECT connection (port 5432), not the
    // pooler (6543), because the pooler does not support the advisory locks
    // Prisma needs. Set MIGRATE_DATABASE_URL to the direct URL; the app runtime
    // keeps using DATABASE_URL (the pooler) via the pg driver adapter.
    url:
      process.env["MIGRATE_DATABASE_URL"] ??
      process.env["DATABASE_URL"],
  },
});
